# Generated by Django 2.2.4 on 2020-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('userHash', models.CharField(blank=True, max_length=255)),
                ('userRole', models.CharField(blank=True, max_length=20)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('createdUser', models.EmailField(max_length=254)),
            ],
        ),
    ]
