# Generated by Django 2.2.4 on 2020-03-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdUser',
            new_name='created_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userHash',
            new_name='user_hash',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userRole',
            new_name='user_role',
        ),
    ]
