# Generated by Django 2.2.4 on 2020-05-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='url_doc',
            new_name='doc_filename',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_user',
            field=models.CharField(max_length=50),
        ),
    ]
