# Generated by Django 2.2.4 on 2020-03-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20200322_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete'),
        ),
        migrations.AddField(
            model_name='parent',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete'),
        ),
    ]
