# Generated by Django 2.2.4 on 2020-03-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20200328_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='image',
            new_name='document_url',
        ),
    ]
