# Generated by Django 2.2.4 on 2020-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20200329_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='enrollment_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='enrollment_year',
            field=models.IntegerField(default=0),
        ),
    ]
