# Generated by Django 2.2.4 on 2020-05-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20200329_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='enrollment_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='enrollment_year',
            field=models.IntegerField(default=0),
        ),
    ]
