# Generated by Django 2.2.4 on 2020-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_auto_20200511_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
