# Generated by Django 2.2.4 on 2020-05-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_auto_20200503_1633'),
        ('athletes', '0007_auto_20200511_2135'),
    ]

    operations = [
    ]
