# Generated by Django 2.2.4 on 2020-05-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_athlete_edited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='created_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_user',
            field=models.CharField(max_length=50),
        ),
    ]
