# Generated by Django 2.2.4 on 2020-05-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_athlete_edited_date'),
        ('athletes', '0008_merge_20200512_2230'),
    ]

    operations = [
    ]
