# Generated by Django 2.2.4 on 2020-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_auto_20200516_2256'),
        ('athletes', '0009_merge_20200516_1053'),
    ]

    operations = [
    ]
