# Generated by Django 2.2.4 on 2020-05-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0010_parent_career'),
        ('athletes', '0010_merge_20200517_1051'),
    ]

    operations = [
    ]
